name: SimpleVoiceRadio
version: '0.0.4'
main: org.nyt.simpleVoiceRadio.SimpleVoiceRadio
api-version: '1.21'
author: Nybik_YT
website: https://modrinth.com/plugin/simple-voice-radio
description: Plugin that adds a radio block that lets players communicate over distances
permissions:
  simple_voice_radio.broadcast_audio:
    description: Can player broadcast audio to all output radios?
    default: op
  simple_voice_radio.command:
    description: Can player see the plugin`s command?
    default: op
  simple_voice_radio.reload_config:
     description: Can player reload plugin`s config?
     default: op
  simple_voice_radio.give:
     description: Can player give radio?
     default: op
  simple_voice_radio.can_craft:
     description: Can player craft radio-block?
     default: true
  simple_voice_radio.can_change_frequency:
     description: Can player specify radio-block frequency?
     default: true
  simple_voice_radio.can_switch_mode:
    description: Can player switch radio-block mode?
    default: true
  simple_voice_radio.can_broadcast:
     description: Can player broadcast via radio-block?
     default: true

dependencies:
  server:
    voicechat:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    CustomDiscs:
      load: BEFORE
      required: false
      join-classpath: true